apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  # Identity allocation mode selects how identities are shared between cilium
  # nodes.  Possible values are "crd" or "kvstore".
  identity-allocation-mode: crd

  # If you want to run cilium in debug mode change this value to true
  debug: "false"

  # The agent can be put into the following three policy enforcement modes
  # default, always and never.
  enable-policy: "default"

  # Enable IPv4 connectivity
  enable-ipv4: "true"

  # Enable IPv6 connectivity
  enable-ipv6: "false"

  # Enable L7 proxy
  enable-l7-proxy: "true"

  # Enable host reachable services
  enable-host-reachable-services: "true"

  # Enable BPF masquerading
  enable-bpf-masquerade: "true"

  # Enable BPF clock source
  enable-bpf-clock-probe: "true"

  # Enable Hubble
  enable-hubble: "true"

  # Hubble metrics server
  hubble-metrics:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http

  # Hubble relay
  hubble-relay-enabled: "true"

  # Hubble UI
  hubble-ui-enabled: "true"

  # Cluster name
  cluster-name: "homelab"

  # Cluster ID
  cluster-id: "1"

  # Enable endpoint health checking
  enable-endpoint-health-checking: "true"

  # Enable health checking between nodes
  enable-health-check-nodeport: "true"

  # Enable local redirect policy
  enable-local-redirect-policy: "false"

  # Enable socket load balancing
  enable-socket-lb: "true"

  # Enable external IPs
  enable-external-ips: "true"

  # Enable node port
  enable-node-port: "true"

  # Enable host port
  enable-host-port: "true"

  # Enable bandwidth manager
  enable-bandwidth-manager: "true"

  # Enable BBR congestion control
  enable-bbr: "true"

  # Enable high scale identity
  enable-high-scale-identity: "true"

  # Enable remote node identity
  enable-remote-node-identity: "true"

  # Enable health checking
  enable-health-checking: "true"

  # Enable prometheus metrics
  enable-prometheus-metrics: "true"

  # Prometheus metrics port
  prometheus-serve-addr: ":9962"

  # Enable operator prometheus metrics
  enable-operator-prometheus-metrics: "true"

  # Operator prometheus metrics port
  operator-prometheus-serve-addr: ":9963"
